language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: 3.5
install:
  python setup.py develop
script:
  - coverage run --source=coveralls setup.py test
  - coverage report -m
after_script:
  coveralls --verbose
