language: python
python:
  - 3.3
  - 3.4
matrix:
  allow_failures:
    - python: 3.5
install:
  - python setup.py develop
  - pip install coveralls
script:
  - coverage run --source=trade setup.py test
  - coverage report -m
after_script:
  coveralls --verbose
